import raw from './directories.json';
import type { Community } from './types';

/**
 * 5chan directory codes — the URL vocabulary of the archive.
 *
 * 5chan addresses boards by directory code (/biz/, /pol/), and several boards
 * can compete for one code: the highest-scoring board resolves it, and 5chan
 * rotates to the next one if that board goes offline. 5archive indexes every
 * candidate and serves them together under the code, so a URL like
 * `/biz/thread/<cid>` keeps working across rotations — including after a board
 * drops off the code's list, which is what `former` is for.
 *
 * `directories.json` is generated by `scripts/build-communities.mjs` from
 * bitsocialnet/lists — don't hand-edit it.
 */
export interface Directory {
  /** Directory code, i.e. the URL segment: "biz" for /biz/. */
  code: string;
  /** Display title from the 5chan directory defaults, e.g. "/biz/ - Business & Finance". */
  title: string;
  /** Board addresses listed under the code today, best-scoring first (the order 5chan resolves it in). */
  boards: string[];
  /** Boards once listed under the code and dropped since; their threads stay under the code. */
  former: string[];
}

type RawDirectory = Omit<Directory, 'former'> & { former?: string[] };

export const directories: Directory[] = (raw as RawDirectory[]).map((d) => ({ ...d, former: d.former ?? [] }));

/** Every board archived under a code: the listed ones first, then the former ones. */
export const archivedBoards = (dir: Directory): string[] => [...dir.boards, ...dir.former];

const byCode = new Map(directories.map((d) => [d.code, d]));

/**
 * Board addresses change TLD upstream (`business-and-finance.eth` became
 * `business-and-finance.bso`) while archived posts keep the address they were
 * crawled with, so addresses also resolve by their stem.
 */
const stem = (address: string) => {
  const dot = address.lastIndexOf('.');
  return dot === -1 ? address : address.slice(0, dot);
};

// A board listed under one code today and formerly under another belongs to
// the code that lists it now, as on 5chan; former memberships only fill gaps.
const byAddress = new Map<string, Directory>();
for (const pick of [(d: Directory) => d.boards, (d: Directory) => d.former]) {
  for (const dir of directories) {
    for (const address of pick(dir)) {
      if (!byAddress.has(address)) byAddress.set(address, dir);
      if (!byAddress.has(stem(address))) byAddress.set(stem(address), dir);
    }
  }
}

export const getDirectory = (code: string): Directory | null => byCode.get(code) ?? null;

export const directoryForAddress = (address: string): Directory | null =>
  byAddress.get(address) ?? byAddress.get(stem(address)) ?? null;

/**
 * A board that has never held a directory code is served under its own
 * address, so nothing indexed ever becomes unreachable.
 */
export const adHocDirectory = (community: Community): Directory => ({
  code: community.address,
  title: community.title ?? community.address,
  boards: [community.address],
  former: [],
});

/** URL segment a board's pages live under: its directory code, else its address. */
export const segmentForAddress = (address: string) => directoryForAddress(address)?.code ?? address;

export const boardPath = (address: string) => `/${encodeURIComponent(segmentForAddress(address))}`;

/** Canonical post URL. Like 5chan, replies use their own cid in the thread route. */
export function threadPath(post: { community_address: string; cid: string }): string {
  return `${boardPath(post.community_address)}/thread/${encodeURIComponent(post.cid)}`;
}

/** Fragment id retained for old reply links and in-page targeting. */
export const replyAnchor = (cid: string) => `p${cid}`;
